language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5.9
      dist: trusty
    - php: 5.5
      dist: trusty

before_install: true

install:
  - phpenv config-rm xdebug.ini
  - sudo sed -i 's/LogLevel DEBUG2/LogLevel DEBUG3/g' /etc/ssh/sshd_config
  - eval `ssh-agent -s`
  - travis/setup-secure-shell.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' -a `php -r "echo (int) version_compare(PHP_VERSION, '7.0', '<');"` = "1" ]; then travis/install-php-extensions.sh; fi"
  - travis/setup-composer.sh

script:
  - travis/run-phpunit.sh
  - cat /etc/ssh/sshd_config
  - cat /var/log/messages